name: Lint

on:
  push:
    paths:
    - 'scripts/**'
  pull_request:
    paths:
    - 'scripts/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: ./scripts

jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install ShellCheck
      run: |
        brew update
        brew install shellcheck

    - name: Run ShellCheck defaults.sh
      run: shellcheck defaults.sh
